databases:
  - name: notes-db
    plan: free
    databaseName: notesDB
    user: notes

services:
  - type: web
    plan: free
    name: notes
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn notes_mate.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4