# Generated by Django 5.1.2 on 2024-10-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
